// Generated by CoffeeScript 1.6.3
(function() {
  $('#sub').click(function() {
    var jh, options, ph;
    if (checkForm("#data_form")) {
      ph = $("#pzsx_h").val();
      if (ph < 0 || ph >= 24) {
        alertMsg("批准整改完成时间(时)，必须为0~23");
        return;
      }
      if (ph.length === 1) {
        ph = '0' + ph;
      }
      ph = " " + ph + ":00:00";
      jh = $("#jcsj_h").val();
      if (jh < 0 || jh >= 24) {
        alertMsg("检查时间(时)，必须为0~23");
        return;
      }
      if (jh.length === 1) {
        jh = '0' + jh;
      }
      jh = " " + jh + ":00:00";
      options = new AjaxOptions("#data_form");
      options.put('service_code', 'P12016');
      options.put('jcsj', $('#jcsj').val() + jh);
      options.put('pzsx', $('#pzsx').val() + ph);
      options.sus = function() {
        return reloadPage();
      };
      return $.ajax(options);
    }
  });

}).call(this);
