// Generated by CoffeeScript 1.6.3
(function() {
  var o;

  o = new AjaxOptions();

  o.put('service_code', 'S12023');

  o.put('zt', '2');

  o.isPadBack = false;

  o.sus = function(data) {
    var row, _i, _len, _ref;
    if ((data.yhs != null) && data.yhs.length > 0) {
      _ref = data.yhs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        row.opt = '<a href="#this">验收</a>';
      }
      return padBackTable(data.yhs, '#yhs', false);
    } else {
      return alertMsg('没有需要处理的隐患');
    }
  };

  $.ajax(o);

  $('#yhs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '6') {
      o = new AjaxOptions();
      o.put('service_code', 'S12022');
      o.put('yh_id', rd.yh_id);
      o.isAlert = false;
      o.isPadBack = false;
      o.sus = function(data) {
        var pzsx, row, _i, _len, _ref;
        padBackData(rd, '#yh_dialog');
        _ref = data.zgs;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          row = _ref[_i];
          row.opt = '<a href="#this">查看</a>';
          if (row.yszt === '2') {
            pzsx = row.pzsx;
          }
        }
        padBackTable(data.zgs, '#yh_dialog #zgs', false);
        $('#yh_dialog').dialog('open');
        $('#ysbz_dialog').attr('table_row', r);
        $('#ysbz_dialog #pzsx_d').val(pzsx.substr(0, 10));
        return $('#ysbz_dialog #pzsx_h').val(pzsx.substr(11, 2));
      };
      return $.ajax(o);
    }
  });

  $('#zgs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '5') {
      padBackData(rd, '#zg_dialog');
      return $('#zg_dialog').dialog('open');
    }
  });

  $('#yh_dialog').dialog({
    autoOpen: false,
    height: 550,
    width: 800,
    modal: true,
    buttons: {
      '验收': function() {
        return $('#ysbz_dialog').dialog('open');
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#zg_dialog').dialog({
    autoOpen: false,
    height: 400,
    width: 600,
    modal: true,
    buttons: {
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#ysbz_dialog').dialog({
    autoOpen: false,
    height: 290,
    width: 500,
    modal: true,
    buttons: {
      '提交': function() {
        var a, ph;
        a = notNull('验收备注', '#ysbz_form #ysbz');
        if (a !== 1) {
          return alertMsg(a);
        } else {
          o = new AjaxOptions('#ysbz_form');
          if ($('#ystg_n').attr('checked') != null) {
            if (checkForm("#ysbz_form")) {
              ph = $("#pzsx_h").val();
              if (ph < 0 || ph >= 24) {
                alertMsg("批准整改完成时间(时)，必须为0~23");
                return;
              }
              if (ph.length === 1) {
                ph = '0' + ph;
              }
              ph = " " + ph + ":00:00";
              o.put('pzsx', $('#ysbz_form #pzsx_d').val() + ph);
            } else {
              return;
            }
          }
          o.put('service_code', 'P12022');
          o.put('yh_id', $('#yh_dialog #yh_id').val());
          o.sus = function() {
            var row;
            row = $('#ysbz_dialog').attr('table_row');
            $('#ysbz_dialog #ysbz').val('');
            $('#ysbz_dialog').dialog('close');
            $('#yh_dialog').dialog('close');
            return $("#yhs tbody tr:eq(" + row + ")").fadeOut(800);
          };
          return $.ajax(o);
        }
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $(':radio[name=ystg]').click(function() {
    if ($(this).val() === '1') {
      return $('#pzsx_tr').fadeIn(300);
    } else {
      return $('#pzsx_tr').fadeOut(300);
    }
  });

  $('#pzsx_tr').hide();

}).call(this);
