// Generated by CoffeeScript 1.6.3
(function() {
  var o;

  o = new AjaxOptions();

  o.put('service_code', 'S12021');

  o.put('yhdw', dep);

  o.put('zt', '1');

  o.isPadBack = false;

  o.sus = function(data) {
    var row, _i, _len, _ref;
    if ((data.yhs != null) && data.yhs.length > 0) {
      _ref = data.yhs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        row.opt = '<a href="#this">申请验收</a>';
      }
      return padBackTable(data.yhs, '#yhs', false);
    } else {
      return alertMsg('没有需要处理的隐患');
    }
  };

  $.ajax(o);

  $('#yhs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '6') {
      o = new AjaxOptions();
      o.put('service_code', 'S12022');
      o.put('yh_id', rd.yh_id);
      o.isAlert = false;
      o.isPadBack = false;
      o.sus = function(data) {
        var row, _i, _len, _ref;
        padBackData(rd, '#yh_dialog');
        _ref = data.zgs;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          row = _ref[_i];
          row.opt = '<a href="#this">查看</a>';
        }
        padBackTable(data.zgs, '#yh_dialog #zgs', false);
        $('#yh_dialog').dialog('open');
        return $('#zgbz_dialog').attr('table_row', r);
      };
      return $.ajax(o);
    }
  });

  $('#zgs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '5') {
      padBackData(rd, '#zg_dialog');
      return $('#zg_dialog').dialog('open');
    }
  });

  $('#yh_dialog').dialog({
    autoOpen: false,
    height: 550,
    width: 800,
    modal: true,
    buttons: {
      '申请验收': function() {
        return $('#zgbz_dialog').dialog('open');
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#zg_dialog').dialog({
    autoOpen: false,
    height: 400,
    width: 600,
    modal: true,
    buttons: {
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#zgbz_dialog').dialog({
    autoOpen: false,
    height: 240,
    width: 500,
    modal: true,
    buttons: {
      '提交': function() {
        var a;
        a = notNull('整改备注', '#zgbz_dialog #zgbz');
        if (a !== 1) {
          return alertMsg(a);
        } else {
          o = new AjaxOptions();
          o.put('service_code', 'P12020');
          o.put('yh_id', $('#yh_dialog #yh_id').val());
          o.put('zgbz', $('#zgbz_dialog #zgbz').val());
          o.sus = function() {
            var row;
            row = $('#zgbz_dialog').attr('table_row');
            $('#zgbz_dialog #zgbz').val('');
            $('#zgbz_dialog').dialog('close');
            $('#yh_dialog').dialog('close');
            return $("#yhs tbody tr:eq(" + row + ")").fadeOut(800);
          };
          return $.ajax(o);
        }
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

}).call(this);
