// Generated by CoffeeScript 1.6.3
(function() {
  var d, m;

  d = new Date();

  $('#year').val(d.getFullYear());

  m = d.getMonth() + 1;

  m = m > 9 ? m : "0" + m;

  $('#month').val(m);

  $('#search').click(function() {
    var o, y;
    y = $('#year').val();
    m = $('#month').val();
    o = new AjaxOptions();
    o.put('service_code', 'S11012');
    o.put('begin', "" + y + "-" + m + "-01");
    o.sus = function(data) {
      var row, _i, _len, _ref;
      _ref = data.users;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        row.opt = '<a href="#this">查看详细</a>';
      }
      return padBackTable(data.users, '#users', false);
    };
    return $.ajax(o);
  }).trigger('click');

  $('#users').bind('clicktd', function(e, r, c, rd, td) {
    var o;
    if (c === '5') {
      o = new AjaxOptions();
      o.put('service_code', 'S11013');
      o.put('username', rd.username);
      o.isAlert = false;
      o.sus = function(data) {
        padBackTable(data.logins, '#login_dialog #logins', false);
        return $('#login_dialog').dialog('open');
      };
      return $.ajax(o);
    }
  });

  $("#login_dialog").dialog({
    autoOpen: false,
    height: 550,
    width: 850,
    modal: true,
    buttons: {
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

}).call(this);
