// Generated by CoffeeScript 1.6.3
(function() {
  var tableOrder;

  tableOrder = $.extend(true, {}, tableTheme, {
    aaSorting: [[5, 'desc']]
  });

  $("#yhsgs").dataTable(tableOrder);

  $('.info').click(function() {
    var ind, rd;
    ind = $(this).attr('ind');
    rd = outJson.result[ind];
    padBackData(rd, '#yhsg_dialog');
    return $('#yhsg_dialog').attr({
      yh_id: rd.yh_id,
      r: ind
    }).dialog('open');
  });

  $("#yhsg_dialog").dialog({
    autoOpen: false,
    height: 550,
    width: 800,
    modal: true,
    buttons: {
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

}).call(this);
