// Generated by CoffeeScript 1.6.3
(function() {
  var o;

  o = new AjaxOptions();

  o.put('service_code', 'S12027');

  o.put('yhdw', dep);

  o.put('zt', '1');

  o.isPadBack = false;

  o.sus = function(data) {
    var row, _i, _len, _ref;
    if ((data.yhsgs != null) && data.yhsgs.length > 0) {
      _ref = data.yhsgs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        row.opt = '<a href="#this">核实</a>';
      }
      return padBackTable(data.yhsgs, '#yhsgs', false);
    } else {
      return alertMsg('没有需要处理的隐患收购');
    }
  };

  $.ajax(o);

  $('#yhsgs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '4') {
      padBackData(rd, '#yhsg_dialog');
      $('#yhhs_form #yh_id').val(rd.yh_id);
      return $('#yhsg_dialog').attr({
        yh_id: rd.yh_id,
        r: r
      }).dialog('open');
    }
  });

  $("#yhsg_dialog").dialog({
    autoOpen: false,
    height: 550,
    width: 800,
    modal: true,
    buttons: {
      '核实': function() {
        return $("#yhhs_dialog").dialog("open");
      },
      '不是隐患': function() {
        if (confirm('是否确认?')) {
          o = new AjaxOptions();
          o.put('service_code', 'P12025');
          o.put('yh_id', $("#yhsg_dialog").attr('yh_id'));
          o.put('zgqk', '不是隐患');
          o.sus = function() {
            var row;
            $('#yhsg_dialog').dialog('close');
            row = $('#yhsg_dialog').attr('r');
            return $("#yhsgs tbody tr:eq(" + row + ")").fadeOut(800);
          };
          return $.ajax(o);
        }
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#yhhs_dialog').dialog({
    autoOpen: false,
    height: 320,
    width: 650,
    modal: true,
    buttons: {
      '提交': function() {
        var zh;
        if (checkForm('#yhhs_form')) {
          zh = $('#yhhs_form #zgsj_h').val();
          if (zh > 23 || zh < 0) {
            alertMsg('整改时间（时）必须为0～23');
            return;
          }
          if (zh.length === 1) {
            zh = '0' + zh;
          }
          zh = " " + zh + ":00:00";
          o = new AjaxOptions('#yhhs_form');
          o.put('service_code', 'P12015');
          o.put('zgsj', $('#yhhs_dialog #zgsj_d').val() + zh);
          o.sus = function() {
            var row;
            $('#yhhs_dialog').dialog('close');
            $('#yhsg_dialog').dialog('close');
            row = $('#yhsg_dialog').attr('r');
            return $("#yhsgs tbody tr:eq(" + row + ")").fadeOut(800);
          };
          return $.ajax(o);
        }
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

}).call(this);
