// Generated by CoffeeScript 1.6.3
(function() {
  $('#fxdw').val(dep);

  $('#yhdw').val(dep);

  $('#sub').click(function() {
    var fh, o;
    if (checkForm('#data_form')) {
      fh = $('#fxsj_h').val();
      if (fh > 23 || fh < 0) {
        alertMsg('发现时间（时）必须为0～23');
        return;
      }
      if (fh.length === 1) {
        fh = '0' + fh;
      }
      fh = " " + fh + ":00:00";
      o = new AjaxOptions('#data_form');
      o.put('service_code', 'P12014');
      o.put('fxsj', $('#fxsj').val() + fh);
      o.sus = function() {
        return reloadPage();
      };
      return $.ajax(o);
    }
  });

}).call(this);
