// Generated by CoffeeScript 1.6.3
(function() {
  var o;

  o = new AjaxOptions();

  o.put('service_code', 'S12028');

  o.put('yhlb', '2');

  o.isPadBack = false;

  o.sus = function(data) {
    var row, _i, _len, _ref;
    if ((data.yhsgs != null) && data.yhsgs.length > 0) {
      _ref = data.yhsgs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        row = _ref[_i];
        row.opt = '<a href="#this">认定</a>';
      }
      return padBackTable(data.yhsgs, '#yhsgs', false);
    } else {
      return alertMsg('没有需要处理的隐患收购');
    }
  };

  $.ajax(o);

  $('#yhsgs').bind('clicktd', function(e, r, c, rd, td) {
    if (c === '6') {
      padBackData(rd, '#yhsg_dialog');
      $('#yhrd_form #yh_id').val(rd.yh_id);
      return $('#yhsg_dialog').attr({
        yh_id: rd.yh_id,
        r: r
      }).dialog('open');
    }
  });

  $("#yhsg_dialog").dialog({
    autoOpen: false,
    height: 550,
    width: 800,
    modal: true,
    buttons: {
      '认定': function() {
        return $("#yhrd_dialog").dialog("open");
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

  $('#yhrd_dialog').dialog({
    autoOpen: false,
    height: 320,
    width: 650,
    modal: true,
    buttons: {
      '提交': function() {
        if (checkForm('#yhrd_form')) {
          o = new AjaxOptions('#yhrd_form');
          o.put('service_code', 'P12026');
          o.sus = function() {
            var row;
            $('#yhrd_dialog').dialog('close');
            $('#yhsg_dialog').dialog('close');
            row = $('#yhsg_dialog').attr('r');
            return $("#yhsgs tbody tr:eq(" + row + ")").fadeOut(800);
          };
          return $.ajax(o);
        }
      },
      '关闭': function() {
        return $(this).dialog('close');
      }
    }
  });

}).call(this);
